# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryoID_v2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cryoID(object):
    def setupUi(self, cryoID):
        cryoID.setObjectName("cryoID")
        cryoID.resize(1047, 541)
        self.centralwidget = QtWidgets.QWidget(cryoID)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 771, 191))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gen_queries_button = QtWidgets.QPushButton(self.groupBox)
        self.gen_queries_button.setGeometry(QtCore.QRect(60, 60, 141, 51))
        self.gen_queries_button.setObjectName("gen_queries_button")
        self.density_map_label = QtWidgets.QLabel(self.groupBox)
        self.density_map_label.setGeometry(QtCore.QRect(0, 0, 60, 14))
        self.density_map_label.setObjectName("density_map_label")
        self.hi_res_limit_label = QtWidgets.QLabel(self.groupBox)
        self.hi_res_limit_label.setGeometry(QtCore.QRect(290, 60, 141, 21))
        self.hi_res_limit_label.setObjectName("hi_res_limit_label")
        self.symmetry_label = QtWidgets.QLabel(self.groupBox)
        self.symmetry_label.setGeometry(QtCore.QRect(290, 100, 91, 16))
        self.symmetry_label.setObjectName("symmetry_label")
        self.browse_mrc_file_button = QtWidgets.QPushButton(self.groupBox)
        self.browse_mrc_file_button.setGeometry(QtCore.QRect(640, 20, 113, 32))
        self.browse_mrc_file_button.setObjectName("browse_mrc_file_button")
        self.gq_methods_button = QtWidgets.QPushButton(self.groupBox)
        self.gq_methods_button.setGeometry(QtCore.QRect(360, 130, 281, 51))
        self.gq_methods_button.setObjectName("gq_methods_button")
        self.mrc_file_edit = QtWidgets.QLineEdit(self.groupBox)
        self.mrc_file_edit.setGeometry(QtCore.QRect(380, 20, 261, 21))
        self.mrc_file_edit.setObjectName("mrc_file_edit")
        self.hi_res_limit_edit = QtWidgets.QLineEdit(self.groupBox)
        self.hi_res_limit_edit.setGeometry(QtCore.QRect(430, 60, 111, 21))
        self.hi_res_limit_edit.setObjectName("hi_res_limit_edit")
        self.res_units_label = QtWidgets.QLabel(self.groupBox)
        self.res_units_label.setGeometry(QtCore.QRect(550, 60, 71, 21))
        self.res_units_label.setObjectName("res_units_label")
        self.symmetry_edit = QtWidgets.QLineEdit(self.groupBox)
        self.symmetry_edit.setGeometry(QtCore.QRect(430, 100, 111, 21))
        self.symmetry_edit.setObjectName("symmetry_edit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 220, 823, 211))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.search_pool_button = QtWidgets.QPushButton(self.groupBox_2)
        self.search_pool_button.setGeometry(QtCore.QRect(70, 70, 121, 51))
        self.search_pool_button.setObjectName("search_pool_button")
        self.sp_methods_button = QtWidgets.QPushButton(self.groupBox_2)
        self.sp_methods_button.setGeometry(QtCore.QRect(360, 130, 281, 51))
        self.sp_methods_button.setObjectName("sp_methods_button")
        self.browse_query_file_button = QtWidgets.QPushButton(self.groupBox_2)
        self.browse_query_file_button.setGeometry(QtCore.QRect(640, 30, 113, 32))
        self.browse_query_file_button.setObjectName("browse_query_file_button")
        self.browse_pool_fil_button = QtWidgets.QPushButton(self.groupBox_2)
        self.browse_pool_fil_button.setGeometry(QtCore.QRect(640, 80, 113, 32))
        self.browse_pool_fil_button.setObjectName("browse_pool_fil_button")
        self.query_file_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.query_file_edit.setGeometry(QtCore.QRect(360, 40, 261, 21))
        self.query_file_edit.setObjectName("query_file_edit")
        self.pool_file_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.pool_file_edit.setGeometry(QtCore.QRect(360, 80, 261, 21))
        self.pool_file_edit.setObjectName("pool_file_edit")
        self.query_file_label = QtWidgets.QLabel(self.groupBox_2)
        self.query_file_label.setGeometry(QtCore.QRect(230, 40, 91, 16))
        self.query_file_label.setObjectName("query_file_label")
        self.protein_pool_file_label = QtWidgets.QLabel(self.groupBox_2)
        self.protein_pool_file_label.setGeometry(QtCore.QRect(230, 80, 111, 16))
        self.protein_pool_file_label.setObjectName("protein_pool_file_label")
        self.abort_button = QtWidgets.QPushButton(self.centralwidget)
        self.abort_button.setGeometry(QtCore.QRect(50, 430, 201, 61))
        self.abort_button.setObjectName("abort_button")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(330, 440, 381, 31))
        self.status_label.setObjectName("status_label")
        cryoID.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cryoID)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 22))
        self.menubar.setObjectName("menubar")
        self.menucryoID = QtWidgets.QMenu(self.menubar)
        self.menucryoID.setObjectName("menucryoID")
        self.menuMore_Options = QtWidgets.QMenu(self.menubar)
        self.menuMore_Options.setObjectName("menuMore_Options")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        cryoID.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cryoID)
        self.statusbar.setObjectName("statusbar")
        cryoID.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(cryoID)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(cryoID)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRecent = QtWidgets.QAction(cryoID)
        self.actionRecent.setObjectName("actionRecent")
        self.actionTBD = QtWidgets.QAction(cryoID)
        self.actionTBD.setObjectName("actionTBD")
        self.actionNonesofar = QtWidgets.QAction(cryoID)
        self.actionNonesofar.setObjectName("actionNonesofar")
        self.actionResults_window = QtWidgets.QAction(cryoID)
        self.actionResults_window.setObjectName("actionResults_window")
        self.actionProgress_bar = QtWidgets.QAction(cryoID)
        self.actionProgress_bar.setObjectName("actionProgress_bar")
        self.actionPreviewer = QtWidgets.QAction(cryoID)
        self.actionPreviewer.setObjectName("actionPreviewer")
        self.menucryoID.addSeparator()
        self.menucryoID.addAction(self.actionNew)
        self.menucryoID.addAction(self.actionOpen)
        self.menucryoID.addAction(self.actionRecent)
        self.menuMore_Options.addSeparator()
        self.menuMore_Options.addAction(self.actionTBD)
        self.menuHelp.addAction(self.actionNonesofar)
        self.menuView.addAction(self.actionResults_window)
        self.menuView.addAction(self.actionProgress_bar)
        self.menuView.addAction(self.actionPreviewer)
        self.menubar.addAction(self.menucryoID.menuAction())
        self.menubar.addAction(self.menuMore_Options.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(cryoID)
        QtCore.QMetaObject.connectSlotsByName(cryoID)

    def retranslateUi(self, cryoID):
        _translate = QtCore.QCoreApplication.translate
        cryoID.setWindowTitle(_translate("cryoID", "MainWindow"))
        self.gen_queries_button.setText(_translate("cryoID", "Generate Queries"))
        self.density_map_label.setText(_translate("cryoID", "Density Map"))
        self.hi_res_limit_label.setText(_translate("cryoID", "High Resolution Limit"))
        self.symmetry_label.setText(_translate("cryoID", "Symmetry"))
        self.browse_mrc_file_button.setText(_translate("cryoID", "Browse Files"))
        self.gq_methods_button.setText(_translate("cryoID", "Methods"))
        self.mrc_file_edit.setText(_translate("cryoID", " your_cryoEM_map.mrc"))
        self.hi_res_limit_edit.setText(_translate("cryoID", "3.2"))
        self.res_units_label.setText(_translate("cryoID", "Angstroms"))
        self.symmetry_edit.setText(_translate("cryoID", "Any"))
        self.search_pool_button.setText(_translate("cryoID", "Search Pool"))
        self.sp_methods_button.setText(_translate("cryoID", "Methods"))
        self.browse_query_file_button.setText(_translate("cryoID", "Browse Files"))
        self.browse_pool_fil_button.setText(_translate("cryoID", "Browse Files"))
        self.query_file_edit.setText(_translate("cryoID", " your_cryoEM_map.mrc"))
        self.pool_file_edit.setText(_translate("cryoID", " your_cryoEM_map.mrc"))
        self.query_file_label.setText(_translate("cryoID", "Query File"))
        self.protein_pool_file_label.setText(_translate("cryoID", "Protein Pool File"))
        self.abort_button.setText(_translate("cryoID", "Abort"))
        self.status_label.setText(_translate("cryoID", "Status"))
        self.menucryoID.setTitle(_translate("cryoID", "File"))
        self.menuMore_Options.setTitle(_translate("cryoID", "More Options"))
        self.menuHelp.setTitle(_translate("cryoID", "Help"))
        self.menuView.setTitle(_translate("cryoID", "View"))
        self.actionNew.setText(_translate("cryoID", "New"))
        self.actionOpen.setText(_translate("cryoID", "Open"))
        self.actionRecent.setText(_translate("cryoID", "Recent"))
        self.actionTBD.setText(_translate("cryoID", "TBD"))
        self.actionNonesofar.setText(_translate("cryoID", "TBD"))
        self.actionResults_window.setText(_translate("cryoID", "Results window"))
        self.actionProgress_bar.setText(_translate("cryoID", "Progress bar"))
        self.actionPreviewer.setText(_translate("cryoID", "Previewer"))
