# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryoID_v2_4.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cryoID(object):
    def setupUi(self, cryoID):
        cryoID.setObjectName("cryoID")
        cryoID.resize(869, 576)
        font = QtGui.QFont()
        font.setPointSize(12)
        cryoID.setFont(font)
        self.centralwidget = QtWidgets.QWidget(cryoID)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.top_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_widget.sizePolicy().hasHeightForWidth())
        self.top_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.top_widget.setFont(font)
        self.top_widget.setObjectName("top_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.top_widget_left = QtWidgets.QWidget(self.top_widget)
        self.top_widget_left.setObjectName("top_widget_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.top_widget_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gen_queries_button = QtWidgets.QPushButton(self.top_widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_queries_button.sizePolicy().hasHeightForWidth())
        self.gen_queries_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gen_queries_button.setFont(font)
        self.gen_queries_button.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.gen_queries_button.setObjectName("gen_queries_button")
        self.verticalLayout_2.addWidget(self.gen_queries_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.top_widget_left)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.top_widget_right = QtWidgets.QWidget(self.top_widget)
        self.top_widget_right.setObjectName("top_widget_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.top_widget_right)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_widget_right_1 = QtWidgets.QWidget(self.top_widget_right)
        self.top_widget_right_1.setStyleSheet("/*background-color: rgb(145, 145, 145);")
        self.top_widget_right_1.setObjectName("top_widget_right_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_widget_right_1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.density_map_label = QtWidgets.QLabel(self.top_widget_right_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.density_map_label.setFont(font)
        self.density_map_label.setObjectName("density_map_label")
        self.horizontalLayout.addWidget(self.density_map_label)
        spacerItem4 = QtWidgets.QSpacerItem(73, 15, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.mrc_file_editbox = QtWidgets.QLineEdit(self.top_widget_right_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mrc_file_editbox.setFont(font)
        self.mrc_file_editbox.setObjectName("mrc_file_editbox")
        self.horizontalLayout.addWidget(self.mrc_file_editbox)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.browse_mrc_file_button = QtWidgets.QPushButton(self.top_widget_right_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browse_mrc_file_button.setFont(font)
        self.browse_mrc_file_button.setStyleSheet("/*image: url(:/newPrefix/upload-sign-svgrepo-com.svg);\n"
"image-position: right; */")
        self.browse_mrc_file_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("svg_assets/upload-sign-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_mrc_file_button.setIcon(icon)
        self.browse_mrc_file_button.setObjectName("browse_mrc_file_button")
        self.horizontalLayout.addWidget(self.browse_mrc_file_button)
        spacerItem6 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.top_widget_right_1)
        self.top_widget_right_2 = QtWidgets.QWidget(self.top_widget_right)
        self.top_widget_right_2.setStyleSheet("/*background-color: rgb(145, 145, 145);")
        self.top_widget_right_2.setObjectName("top_widget_right_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_widget_right_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resolution_label = QtWidgets.QLabel(self.top_widget_right_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resolution_label.setFont(font)
        self.resolution_label.setObjectName("resolution_label")
        self.horizontalLayout_3.addWidget(self.resolution_label)
        spacerItem7 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.resolution_editbox = QtWidgets.QLineEdit(self.top_widget_right_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resolution_editbox.setFont(font)
        self.resolution_editbox.setObjectName("resolution_editbox")
        self.horizontalLayout_3.addWidget(self.resolution_editbox)
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.res_units_label = QtWidgets.QLabel(self.top_widget_right_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_units_label.setFont(font)
        self.res_units_label.setObjectName("res_units_label")
        self.horizontalLayout_3.addWidget(self.res_units_label)
        spacerItem9 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.top_widget_right_2)
        self.top_widget_right_3 = QtWidgets.QWidget(self.top_widget_right)
        self.top_widget_right_3.setStyleSheet("/*background-color: rgb(145, 145, 145);")
        self.top_widget_right_3.setObjectName("top_widget_right_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_widget_right_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.symmetry_label = QtWidgets.QLabel(self.top_widget_right_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.symmetry_label.setFont(font)
        self.symmetry_label.setObjectName("symmetry_label")
        self.horizontalLayout_4.addWidget(self.symmetry_label)
        spacerItem10 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.symmetry_editbox = QtWidgets.QLineEdit(self.top_widget_right_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.symmetry_editbox.setFont(font)
        self.symmetry_editbox.setObjectName("symmetry_editbox")
        self.horizontalLayout_4.addWidget(self.symmetry_editbox)
        spacerItem11 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout.addWidget(self.top_widget_right_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.top_widget_right_4 = QtWidgets.QWidget(self.top_widget_right)
        self.top_widget_right_4.setStyleSheet("/*background-color: rgb(85, 85, 85);")
        self.top_widget_right_4.setObjectName("top_widget_right_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.top_widget_right_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gq_methods_button = QtWidgets.QPushButton(self.top_widget_right_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gq_methods_button.setFont(font)
        self.gq_methods_button.setObjectName("gq_methods_button")
        self.horizontalLayout_5.addWidget(self.gq_methods_button)
        spacerItem14 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addWidget(self.top_widget_right_4)
        self.horizontalLayout_6.addWidget(self.top_widget_right, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_7.addWidget(self.top_widget)
        self.mid_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_widget.sizePolicy().hasHeightForWidth())
        self.mid_widget.setSizePolicy(sizePolicy)
        self.mid_widget.setObjectName("mid_widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.mid_widget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.mid_widget_left = QtWidgets.QWidget(self.mid_widget)
        self.mid_widget_left.setObjectName("mid_widget_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mid_widget_left)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem16)
        self.search_pool_button = QtWidgets.QPushButton(self.mid_widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_pool_button.sizePolicy().hasHeightForWidth())
        self.search_pool_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_pool_button.setFont(font)
        self.search_pool_button.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.search_pool_button.setObjectName("search_pool_button")
        self.verticalLayout_5.addWidget(self.search_pool_button)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem17)
        self.horizontalLayout_12.addWidget(self.mid_widget_left)
        spacerItem18 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.mid_widget_right = QtWidgets.QWidget(self.mid_widget)
        self.mid_widget_right.setObjectName("mid_widget_right")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mid_widget_right)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mid_widget_right_1 = QtWidgets.QWidget(self.mid_widget_right)
        self.mid_widget_right_1.setStyleSheet("/*background-color: rgb(145, 145, 145);")
        self.mid_widget_right_1.setObjectName("mid_widget_right_1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.mid_widget_right_1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.query_file_label = QtWidgets.QLabel(self.mid_widget_right_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.query_file_label.setFont(font)
        self.query_file_label.setObjectName("query_file_label")
        self.horizontalLayout_13.addWidget(self.query_file_label)
        spacerItem19 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.query_file_editbox = QtWidgets.QLineEdit(self.mid_widget_right_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.query_file_editbox.setFont(font)
        self.query_file_editbox.setObjectName("query_file_editbox")
        self.horizontalLayout_13.addWidget(self.query_file_editbox)
        spacerItem20 = QtWidgets.QSpacerItem(5, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem20)
        self.browse_query_file_button = QtWidgets.QPushButton(self.mid_widget_right_1)
        self.browse_query_file_button.setText("")
        self.browse_query_file_button.setIcon(icon)
        self.browse_query_file_button.setObjectName("browse_query_file_button")
        self.horizontalLayout_13.addWidget(self.browse_query_file_button)
        spacerItem21 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem21)
        self.verticalLayout_6.addWidget(self.mid_widget_right_1)
        self.mid_widget_right_2 = QtWidgets.QWidget(self.mid_widget_right)
        self.mid_widget_right_2.setStyleSheet("/*background-color: rgb(145, 145, 145);")
        self.mid_widget_right_2.setObjectName("mid_widget_right_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.mid_widget_right_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.protein_pool_file_label = QtWidgets.QLabel(self.mid_widget_right_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.protein_pool_file_label.setFont(font)
        self.protein_pool_file_label.setObjectName("protein_pool_file_label")
        self.horizontalLayout_14.addWidget(self.protein_pool_file_label)
        spacerItem22 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem22)
        self.pool_file_editbox = QtWidgets.QLineEdit(self.mid_widget_right_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pool_file_editbox.setFont(font)
        self.pool_file_editbox.setObjectName("pool_file_editbox")
        self.horizontalLayout_14.addWidget(self.pool_file_editbox)
        spacerItem23 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem23)
        self.browse_pool_fil_button = QtWidgets.QPushButton(self.mid_widget_right_2)
        self.browse_pool_fil_button.setText("")
        self.browse_pool_fil_button.setIcon(icon)
        self.browse_pool_fil_button.setObjectName("browse_pool_fil_button")
        self.horizontalLayout_14.addWidget(self.browse_pool_fil_button)
        spacerItem24 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem24)
        self.verticalLayout_6.addWidget(self.mid_widget_right_2)
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem25)
        self.mid_widget_right_3 = QtWidgets.QWidget(self.mid_widget_right)
        self.mid_widget_right_3.setStyleSheet("/*background-color: rgb(85, 85, 85);")
        self.mid_widget_right_3.setObjectName("mid_widget_right_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.mid_widget_right_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem26 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem26)
        self.sp_options_button = QtWidgets.QPushButton(self.mid_widget_right_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sp_options_button.setFont(font)
        self.sp_options_button.setObjectName("sp_options_button")
        self.horizontalLayout_15.addWidget(self.sp_options_button)
        spacerItem27 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem27)
        self.verticalLayout_6.addWidget(self.mid_widget_right_3)
        self.horizontalLayout_12.addWidget(self.mid_widget_right)
        self.verticalLayout_7.addWidget(self.mid_widget)
        self.bot_widget = QtWidgets.QWidget(self.centralwidget)
        self.bot_widget.setObjectName("bot_widget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.bot_widget)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem28 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem28)
        self.abort_button = QtWidgets.QPushButton(self.bot_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.abort_button.setFont(font)
        self.abort_button.setStyleSheet("background-color: rgb(206, 0, 0);")
        self.abort_button.setObjectName("abort_button")
        self.horizontalLayout_16.addWidget(self.abort_button)
        spacerItem29 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem29)
        self.status_label = QtWidgets.QLabel(self.bot_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_label.setFont(font)
        self.status_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_16.addWidget(self.status_label)
        spacerItem30 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem30)
        self.status_label_ = QtWidgets.QLabel(self.bot_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label_.sizePolicy().hasHeightForWidth())
        self.status_label_.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_label_.setFont(font)
        self.status_label_.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.status_label_.setObjectName("status_label_")
        self.horizontalLayout_16.addWidget(self.status_label_)
        spacerItem31 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem31)
        self.save_button = QtWidgets.QPushButton(self.bot_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("background-color: rgb(0, 204, 0);")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_16.addWidget(self.save_button)
        spacerItem32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem32)
        self.verticalLayout_7.addWidget(self.bot_widget)
        cryoID.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cryoID)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 28))
        self.menubar.setObjectName("menubar")
        self.menucryoID = QtWidgets.QMenu(self.menubar)
        self.menucryoID.setObjectName("menucryoID")
        self.menuMore_Options = QtWidgets.QMenu(self.menubar)
        self.menuMore_Options.setObjectName("menuMore_Options")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        cryoID.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cryoID)
        self.statusbar.setObjectName("statusbar")
        cryoID.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(cryoID)
        self.dockWidget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem33)
        self.dockWidget.setWidget(self.dockWidgetContents)
        cryoID.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionNew = QtWidgets.QAction(cryoID)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(cryoID)
        self.actionOpen.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRecent = QtWidgets.QAction(cryoID)
        self.actionRecent.setObjectName("actionRecent")
        self.actionTBD = QtWidgets.QAction(cryoID)
        self.actionTBD.setObjectName("actionTBD")
        self.actionNonesofar = QtWidgets.QAction(cryoID)
        self.actionNonesofar.setObjectName("actionNonesofar")
        self.actionResults_window = QtWidgets.QAction(cryoID)
        self.actionResults_window.setObjectName("actionResults_window")
        self.actionProgress_bar = QtWidgets.QAction(cryoID)
        self.actionProgress_bar.setObjectName("actionProgress_bar")
        self.actionPreviewer = QtWidgets.QAction(cryoID)
        self.actionPreviewer.setObjectName("actionPreviewer")
        self.action_L_oad_save = QtWidgets.QAction(cryoID)
        self.action_L_oad_save.setObjectName("action_L_oad_save")
        self.actionPhenix = QtWidgets.QAction(cryoID)
        self.actionPhenix.setObjectName("actionPhenix")
        self.menucryoID.addSeparator()
        self.menucryoID.addAction(self.actionNew)
        self.menucryoID.addAction(self.actionOpen)
        self.menucryoID.addAction(self.actionRecent)
        self.menucryoID.addAction(self.action_L_oad_save)
        self.menuMore_Options.addSeparator()
        self.menuMore_Options.addAction(self.actionTBD)
        self.menuMore_Options.addAction(self.actionPhenix)
        self.menuHelp.addAction(self.actionNonesofar)
        self.menuView.addAction(self.actionResults_window)
        self.menuView.addAction(self.actionProgress_bar)
        self.menuView.addAction(self.actionPreviewer)
        self.menubar.addAction(self.menucryoID.menuAction())
        self.menubar.addAction(self.menuMore_Options.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(cryoID)
        QtCore.QMetaObject.connectSlotsByName(cryoID)

    def retranslateUi(self, cryoID):
        _translate = QtCore.QCoreApplication.translate
        cryoID.setWindowTitle(_translate("cryoID", "MainWindow"))
        self.gen_queries_button.setToolTip(_translate("cryoID", "<html><head/><body><p>Specify your cryoEM density map, resolution limit, and symmetry in the fields to the right, then click on this button to generate query sequences from your chosen cryoEM map.</p></body></html>"))
        self.gen_queries_button.setText(_translate("cryoID", "Generate Queries"))
        self.density_map_label.setText(_translate("cryoID", "Density Map"))
        self.mrc_file_editbox.setText(_translate("cryoID", "your_cryoEM_map.mrc"))
        self.browse_mrc_file_button.setToolTip(_translate("cryoID", "<html><head/><body><p>Browse files and select the cryoEM density map you would like to analyze.</p></body></html>"))
        self.resolution_label.setText(_translate("cryoID", "High Resolution Limit"))
        self.resolution_editbox.setText(_translate("cryoID", "3.2"))
        self.res_units_label.setText(_translate("cryoID", "Angstroms"))
        self.symmetry_label.setText(_translate("cryoID", "Symmetry"))
        self.symmetry_editbox.setText(_translate("cryoID", "Any"))
        self.gq_methods_button.setText(_translate("cryoID", "Options"))
        self.search_pool_button.setToolTip(_translate("cryoID", "<html><head/><body><p>Specify your query set file and your candidate protein pool file in the fields to the right, then click on this button to identify the candidate proteins that align best with your query sequences.</p></body></html>"))
        self.search_pool_button.setText(_translate("cryoID", "Search Pool"))
        self.query_file_label.setText(_translate("cryoID", "Query File"))
        self.query_file_editbox.setText(_translate("cryoID", "your_query_file"))
        self.protein_pool_file_label.setText(_translate("cryoID", "Protein Pool File       "))
        self.pool_file_editbox.setText(_translate("cryoID", "your_pool_file"))
        self.sp_options_button.setText(_translate("cryoID", "Options"))
        self.abort_button.setToolTip(_translate("cryoID", "<html><head/><body><p>Abort the current job</p></body></html>"))
        self.abort_button.setText(_translate("cryoID", "Abort"))
        self.status_label.setText(_translate("cryoID", "Status"))
        self.status_label_.setText(_translate("cryoID", "  -/-"))
        self.save_button.setToolTip(_translate("cryoID", "<html><head/><body><p>Saves most recent progress that can be loaded and resumed at a later time. (Ctrl+S)</p></body></html>"))
        self.save_button.setWhatsThis(_translate("cryoID", "<html><head/><body><p><br/></p></body></html>"))
        self.save_button.setText(_translate("cryoID", "Save"))
        self.menucryoID.setTitle(_translate("cryoID", "File"))
        self.menuMore_Options.setTitle(_translate("cryoID", "More Options"))
        self.menuHelp.setTitle(_translate("cryoID", "Help"))
        self.menuView.setTitle(_translate("cryoID", "View"))
        self.label_2.setText(_translate("cryoID", "side menu"))
        self.label.setText(_translate("cryoID", "(just testing)"))
        self.actionNew.setText(_translate("cryoID", "New"))
        self.actionOpen.setText(_translate("cryoID", "Open"))
        self.actionRecent.setText(_translate("cryoID", "Recent"))
        self.actionTBD.setText(_translate("cryoID", "COOT"))
        self.actionNonesofar.setText(_translate("cryoID", "TBD"))
        self.actionResults_window.setText(_translate("cryoID", "Results window"))
        self.actionProgress_bar.setText(_translate("cryoID", "Progress bar"))
        self.actionPreviewer.setText(_translate("cryoID", "Previewer"))
        self.action_L_oad_save.setText(_translate("cryoID", "Load save"))
        self.actionPhenix.setText(_translate("cryoID", "Phenix"))
from svg_assets import resources
